name = "peptideos"
main = "worker/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "peptideos_db"
database_id = "c2314e19-d18a-4269-bebe-65dd5d85c6c6"

[[kv_namespaces]]
binding = "SESSIONS"
id = "740034324a014312b217e995ea0326b3"

[triggers]
crons = ["*/5 * * * *"]

[vars]
APP_URL = "https://peptideos.cwenterprises.net"

[assets]
directory = "."
binding = "ASSETS"
